//This Code is autogenerated by Fredy Resources Code Generation
//Please, do not modify by hand

#pragma once
#include <string>

class x64
{
private:
    x64(){}
public:

    class Debug
    {
    private:
        Debug(){}
    public:
        inline static const std::string ClassCode_obj = "ClassCode.obj";
        inline static const std::string FileItem_obj = "FileItem.obj";
        inline static const std::string FileTree_obj = "FileTree.obj";
        inline static const std::string ResourceGen_exe = "ResourceGen.exe";
        inline static const std::string ResourceGen_exe_recipe = "ResourceGen.exe.recipe";
        inline static const std::string ResourceGen_ilk = "ResourceGen.ilk";
        inline static const std::string ResourceGen_log = "ResourceGen.log";
        inline static const std::string ResourceGen_obj = "ResourceGen.obj";
        inline static const std::string ResourceGen_pdb = "ResourceGen.pdb";

        class ResourceGen_tlog
        {
        private:
            ResourceGen_tlog(){}
        public:
            inline static const std::string CL_command_1_tlog = "ResourceGen.tlog/CL.command.1.tlog";
            inline static const std::string CL_read_1_tlog = "ResourceGen.tlog/CL.read.1.tlog";
            inline static const std::string CL_write_1_tlog = "ResourceGen.tlog/CL.write.1.tlog";
            inline static const std::string link_command_1_tlog = "ResourceGen.tlog/link.command.1.tlog";
            inline static const std::string link_read_1_tlog = "ResourceGen.tlog/link.read.1.tlog";
            inline static const std::string link_write_1_tlog = "ResourceGen.tlog/link.write.1.tlog";
            inline static const std::string ResourceGen_lastbuildstate = "ResourceGen.tlog/ResourceGen.lastbuildstate";
        };

        inline static const std::string ResourceGen_vcxproj_FileListAbsolute_txt = "ResourceGen.vcxproj.FileListAbsolute.txt";
        inline static const std::string vc143_idb = "vc143.idb";
        inline static const std::string vc143_pdb = "vc143.pdb";
    };

};

//END OF AUTO-GENERATED CODE
